#client名称和端口
server:
  port: 8090
  name: my-sentinel-clinet

#sentinel注册到dashboard
spring:
  application:
    name: spring-cloud-gateway
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
    #eager: true