#server:
#  port: 8090
#spring:
#  application:
#    name: spring-cloud-gateway
#  cloud:
#    nacos:
#      config:
#        server-addr: 127.0.0.1:8848
#        group: DEFAULT_GROUP
#        file-extension: yaml
#        enabled: false
#      discovery:
#        server-addr: 127.0.0.1:8848
#    gateway:
#      routes:
#        - id: path_route
#          uri: http://127.0.0.1:8001/
#          predicates:
#            - Path=/mz/**